In [35]:
import tensorflow as tf

In [36]:
import numpy as np
from tensorflow.keras.datasets import mnist
# from tensorflow.keras.utils.np_utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Conv2D, MaxPooling2D,Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint

import skimage.io as io

In [37]:
(X_train, y_train),(X_test, y_test) = mnist.load_data()

In [49]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)
(60000, 10)
(10000, 10)


In [39]:
X_train = X_train.reshape(-1,28,28,1)
X_test = X_test.reshape(-1,28,28,1)
X_train = X_train / 255
X_test = X_test / 255

In [48]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [41]:
import tensorflow.keras.utils as utils

In [42]:
y_train = utils.to_categorical(y_train, num_classes=10) # 独热编码
y_test = utils.to_categorical(y_test, num_classes=10)

print(y_train)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [43]:
model_checkpoint = ModelCheckpoint("lenet-5-tf.h5", monitor="loss", verbose=1, save_best_only=True)

In [46]:
model = Sequential()
model.add(Conv2D(input_shape=(28,28,1), kernel_size=(5,5), filters=20, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=2, padding="same"))

model.add(Conv2D(kernel_size=(5,5), filters=20, activation="relu", padding="same"))
model.add(MaxPooling2D(pool_size=(2,2), strides=2, padding="same"))

model.add(Flatten())
model.add(Dense(500, activation="relu"))
model.add(Dense(10, activation="softmax"))
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=['accuracy'])

print("trainning....")
model.fit(X_train, y_train, epochs=2, batch_size=32, callbacks=[model_checkpoint])

print("\n Testing")
model.load_weights("lenet-5-tf.h5")
loss, accuracy = model.evaluate(X_test, y_test)

trainning....
Train on 60000 samples
Epoch 1/2
59904/60000 [============================>.] - ETA: 0s - loss: 0.1300 - accuracy: 0.9593
Epoch 00001: loss did not improve from 0.04299
60000/60000 [==============================] - 34s 568us/sample - loss: 0.1300 - accuracy: 0.9594
Epoch 2/2
59936/60000 [============================>.] - ETA: 0s - loss: 0.0421 - accuracy: 0.9868
Epoch 00002: loss improved from 0.04299 to 0.04205, saving model to lenet-5-tf.h5
60000/60000 [==============================] - 29s 490us/sample - loss: 0.0421 - accuracy: 0.9868

 Testing
10000/10000 [==============================] - 10s 992us/sample - loss: 0.0309 - accuracy: 0.9901


In [47]:
print( loss)
print( accuracy)

0.030925846976460888
0.9901
